theme: jekyll-theme-minimal
title: Open MultiBoxing (Opensource, safe, free, Multiboxing)
description: Open Source rules compliant multiboxing/dual-boxing.
logo: OpenMultiBoxing.png
show_downloads: false
github.is_project_page: false
